import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Spottunes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html data-lt-installed="true" lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
